-# COMP2911 - Project - Diary Extractor
-#
-# what did I do yesterday?
-# what will I do today?
Add a comment to this line
-# is anything in my way?
-#
-
-######  TEMPLATE  ######
-Date :
-> what did I do yesterday?
-> What will I do today?
-> is anything in my way?
-########################
-
-
-##### NEW WEEK #####
-
-
-Date : 27/04/16
-> what did I do yesterday?
-I discussed individual roles with my team.
-> what will I do today?
-I will reformat the back end code to allow for a cleaner design.
-> is anything in my way?
-Procrastination.
-
-Date : 29/04/16
-> what did I do yesterday?
-I reformatted the back end code.
-> what will I do today?
-I will improve the speed and memory usage of the maze generation code. Considering it uses recursive backtracking it uses a lot of memory and needs to be made more efficient.
-> is anything in my way?
-Gandalf won't let me pass...
-
-
-Date : 30/04/16
-> what did I do yesterday?
-I improved the speed and memory usage of the maze by changing data types and removing unecessary checks. (I should have done timed tests to see the improvement)
-> what will I do today?
-I will write the Javadocs for each class and methods I have written.
-> is anything in my way?
-Maybe I should first finish the UML diagram instead of trying to avoid it
-
-
-Date : 02/04/16
-> what did I do yesterday?
-I wrote Javadocs for all method and classes.
-> What will I do today?
-I will prepare my diary for tomorrow so I can show my tutor how productive I can be
-> is anything in my way?
-My desire for food will kill me one day...
-
-
-
-##### NEW WEEK #####
-
-
-
-Date : 04/04/16
-> what did I do yesterday?
-I attended the tutorial and worked on the project with my team
-> What will I do today?
-Document myself on Java Swing and try to start implementing the basic view of the maze
-> is anything in my way?
-My lack of knowledge on Java Swing
-
-
-Date : 06/04/16
-> what did I do yesterday?
-I learned the basics of Swing and implemented a test app that creates a frame and a Jpanel
-> What will I do today?
-I will add the Maze to the Gui and will represent it as a Grid of squares.
-> is anything in my way?
-N/A
-
-Date : 07/04/16
-> what did I do yesterday?
-I implemented the grid for the Maze and wrote the paintComponent function
-> What will I do today?
-I will fix some of the code, add Javadocs and comments for the implemented methods
-> is anything in my way?
-The cat sometimes sits on the keyboard... He's kind of in the way.
-
-Date : 08/04/16
-> what did I do yesterday?
-I fixed issues with the code
-> What will I do today?
-I will change the colors of the maze and attempt to add a Keylistener to allow the maze to be playable
-> is anything in my way?
-Cat walked away from the keyboard but he's left plenty of fur on it... I hate this cat sometimes...
-
-Date : 09/04/16
-> what did I do yesterday?
-I started implementing the Keylistener. Came accross a problem where the Key events would not be triggered.
-Figure out that I forgot to add the KeyListeners to some of the components.
-> What will I do today?
-I will connect the KeyEvents with the back end of the maze to allow the maze to be playable.
-> is anything in my way?
-I will not discuss any issues without my lawyer.
-
-
-
-##### NEW WEEK #####
